### ISSUE TITLE
Networks cache bug: too long name 

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/pcviz#35]
E.g. (despite someone sent weird and too long ID list) : 

java.nio.file.FileSystemException: data/cached/networks/-PROM1TACO1 TCP10C ATXN2 PANX1 2810004N23RIK ADAMTS5 DDX3Y LRRN2 NSUN2 VIM - MDM1 GLIS3 FLNA PAX6 PPIF - ACTB DES EEF2 RBBP8 GOLGA7B UBE3B - CYP26B1 SLC29A1 C6 IPMK SAR1B - YWHAE LYSMD2 VMN1R194 LONRF3 YLPM1 - NFX1 TGFBR2 PTPN12 MTMR3 UNC5B CDK5RAP3 IDH1 IFT74 SRSF7 - SLAIN2 FBXW11 PSME1 - VIM - FAM19A2 - DDC RIOK2 TCP10C LDOC1L VIM TPM4 TICAM1 GM4858 - - PODN - CALR P4HA1 FAM76B XPO5 ADAMTSL1 INTS6L CTNNA1 - FABP12 UBR3 PLG PROM1 - LTBP3 - - PLA2G4A DES MIGA2 MFHAS1 PIWIL4 CEP63 BAZ1A - DCXR LGALS3 PRG4 OLFR572 - - - SLC22A19 APRT - - - - ADCK5 - BFSP2 - TACO1 PTPN21 MYO6 MIOS - CDCA8 TCP10A SEC11A - PCDH15 OTX2 DNAJC27 ARF2 MCG1038069 PDIA3 - NNAT - SRSY PPP1R9A HSPA8 INPP4A - EEF1G DIAPH1 - - SLC25A21 ABCD2 RPL5 DLGAP1 CACNA1E ITPR3 FSIP2 ATP4A - ACTB - - - SCHIP1 SATB2 - FAM114A1 - KCTD1 RPS6KC1 CTTNBP2NL PTPRJ ZFP128 C1RA - WDR19 H2AFJ RPL23 ELL ST18 RPL18 RPL18 WDR19 ARHGEF17 RMND5A - DGKG KHDC3 KRT72 - RPS8 - MKL1 - SLC26A2 GLUD1 RGS6 - RPL34 - - PSMA3 SREK1 - WISP1 - PARK7 MTCL1 EED - - HNRNPR GRN - METTL3 WWP1 - PHLDA1 - - - MKL1P84022.json: File name too long
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[na:1.8.0_66]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_66]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_66]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_66]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[na:1.8.0_66]
        at java.nio.file.Files.newOutputStream(Files.java:216) ~[na:1.8.0_66]
        at java.nio.file.Files.write(Files.java:3292) ~[na:1.8.0_66]
        at org.pathwaycommons.pcviz.service.PathwayCommonsService.createNetwork(PathwayCommonsService.java:183) ~[classes!/:2.3.0-SNAPSHOT]
        at org.pathwaycommons.pcviz.service.PathwayCommonsService$$FastClassBySpringCGLIB$$e544089e.invoke(<generated>) ~[classes!/:2.3.0-SNAPSHOT]
...

**Comment by IgorRodchenkov** [comment]
FYI: this happened mostly when a user sent a very long malformed gene list (IDs must be separated with comas - not with spaces, etc..) via pcviz query URL.

Fixed (cache file name is now generated from the sorted IDs using MD5 hash), closed.
